### ISSUE TITLE
Passed FsCheck properties are not shown in output

### ISSUE THREAD

**Issue by rexcfnghk** [xunit/resharper-xunit#104]
When a FsCheck `Property` test is run and passed, I expected something like:

    Ok, passed 100 tests

to be shown in the output window. However this is not shown in the unit test session window. Output from failed tests are shown correctly in the output.

I am using the following NuGet package to bridge FsCheck and XUnit:
- FsCheck.Xunit

Minimal example to show this:

```fsharp
// SUT
let add x y = x + y

// Test
open FsCheck.Xunit

[<Property>]
let ``Add function is communicative`` x y =
    add x y = add y x
```

The unit test session window simply shows

> Add function is communicative passed

without the output shown above. Is there any settings on the plugin side to include this output? I did get the output using the `xunit.consolerunner` NuGet package and running the test in VS's native Test Explorer.

**Comment by citizenmatt** [comment]
This is because FsCheck isn't sending an "output" message, but [adding the output to the final result](https://github.com/fscheck/FsCheck/blob/master/src/FsCheck.Xunit/PropertyAttribute.fs#L149). The ReSharper runner only uses the output messages, as I want to show output as it happens. I don't look at the final output, to avoid reporting it twice, once as it happens, and once more at the end.

I'm not sure what's the best way to handle this. @bradwilson, what's the intent for the `Output` property on `ITestResultMessage`? Is it supposed to be _only_ the output reported by `ITestOutput`, or can it also contain extra output? Extra output would be awkward, unless it's at the start or end, and even then it would require caching output and comparing...

I'm inclined to file this as a bug against FsCheck itself (the console runner + vs presumably don't report messages as they happen), although it would be nice to handle the scenario directly.

**Comment by bradwilson** [comment]
The `Output` parameter of `ITestResultMessage` is intended to be the complete output from the test. This is what's used in the XML (and related transforms).

From a contractual point of view, I would like to say that it's required that all the output in `ITestResultMessage.Output` has been reported via an `ITestOutput` message; if it can't be done "live" (because it's being computed at the end, rather than being output via some live output collection method), then it must still be sent as a single `ITestOutput` message just before the results of the test are reported.

That said, I know that 1.x does not have live output, so I will need to ensure that I am following my own rules. :-p

**Comment by bradwilson** [comment]
Okay, I did verify that the 1.x adapter is doing the right thing, even with a comment about why:

```csharp
// Since we don't get live output from xUnit.net v1, we just send a single output message just before
// the result message (if there was any output).
if (!string.IsNullOrEmpty(output))
    @continue = messageSink.OnMessage(new TestOutput(currentTest, output)) && @continue;
```

https://github.com/xunit/xunit/blob/5e24b60013fa7c1783edb0f11f025624feaaad4e/src/xunit.runner.utility.desktop/Frameworks/v1/TestClassCallbackHandler.cs#L129-L132

**Comment by citizenmatt** [comment]
Thanks Brad. I've raised a PR against FsCheck to get this fixed. I'm going to close this as there's not much I can do in the runner.

**Comment by CumpsD** [comment]
How did you get R# to detect your FsCheck tests? Just installed the runner and it worked?

**Comment by rexcfnghk** [comment]
@CumpsD Install the runner and you can run FsCheck properties from the unit test explorer.

**Comment by CumpsD** [comment]
Indeed, right clicking doesnt work, but from the explorer they show up. but only if I turn it into a Console project, weirdness ;)

Thanks

**Comment by citizenmatt** [comment]
Shouldn't require a console project, but they're only detected from compiled code, as ReSharper doesn't understand F# source files. Hitting the refresh button in the test explorer can help if they're not already shown.
