### ISSUE TITLE
Cannot use Resharper Test Session

### ISSUE THREAD

**Issue by tebeco** [xunit/resharper-xunit#125]
I'm not sure the issue comes from this but i'll see

Context :
- Vs2015 Update 3 (+KB since Update 3)
- .Net Core RTM 1.0.0 + associated SDK (latest RTM + associated SDK)
- dotnet.exe version : 1.0.0-preview2-003121 (latest CLI 'official')
- Resharper Ultimate 2016.1.2 (latest)

Project :
- .Net Core> Class Library

From url :
https://xunit.github.io/docs/getting-started-dotnet-core.html

Project.json:

```
{
  "version": "1.0.0-*",
  "testRunner": "xunit",

  "dependencies": {
    "xunit": "2.2.0-beta2-build3300",
    "dotnet-test-xunit": "2.2.0-preview2-build1029"
  },

  "frameworks": {
    "netcoreapp1.0": {
      "dependencies": {
        "Microsoft.NETCore.App": {
          "type": "platform",
          "version": "1.0.0"
        }
      }
    }
  }
}
```

Test class :

```
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Xunit;

namespace XunitNetCoreSample
{
    public class Class1
    {
        [Fact]
        public void PassingTest()
        {
            Assert.Equal(4, Add(2, 2));
        }

        [Fact]
        public void FailingTest()
        {
            Assert.Equal(5, Add(2, 2));
        }

        int Add(int x, int y)
        {
            return x + y;
        }
    }
}
```
- As the Readme shows, the test run if I use the Test Explorer from Visual Studio
- Running it from Resharper or dotCover + Continous Test endup in 2 successive error :

![image](https://cloud.githubusercontent.com/assets/2266487/17253746/52dd1c82-55b2-11e6-858b-d3bc157a61b0.png)

![image](https://cloud.githubusercontent.com/assets/2266487/17253759/5eb4f822-55b2-11e6-94dd-a0f9ea2b3d80.png)
- What did I missed ?
- Am I asking the question on the good repository ?
- Is it a bug ?
- Is there a workaround ?
- Is there a date for a fix it it's a known issue

**Comment by citizenmatt** [comment]
.net core tests aren't supported by ReSharper right now - it'll be coming in 2016.3. It was planned for 2016.2 (the version due any minute now), but it didn't get finished and stable in time. The 2016.3 EAP will start shortly after the 2016.2 release, so in a few weeks time.

The xunit support is now in the box with ReSharper, rather than as a plugin, so technically the best place for bug reports is https://youtrack.jetbrains.com, although I'm happy to answer here, too. I should probably close this repo, really…

Going to close this in favour of #38
