### ISSUE TITLE
Issue when using Exude

### ISSUE THREAD

**Issue by kerams** [xunit/resharper-xunit#24]
https://github.com/GreanTech/Exude is an extension for xunit that allows to write unit tests as methods returning IEnumerables of test cases.
I can define test cases in F# like this:

    [<FirstClassTests>]
    let testCases () = seq {
                          yield TestCase(fun () -> Assert.Equal (1, 1))
                          yield TestCase(fun () -> Assert.Equal (1, 2))
                          yield TestCase(fun () -> Assert.Equal (1, 3))
                        } 

R#'s runner picks it up fine and runs all 3. However, the results are returned like this:
![Runner](http://i60.tinypic.com/n718g.png) As you can see, the problem is the fact that the entire method with 3 test cases is represented as one node. It would be nice if I could see separate nodes for each test case, as if each was a standard `[Fact]`.

Xunit's console runner does indeed show these as 3 separate tests, but they seem to have the same name (testCases) -- could that be the reason why they are grouped under one node in R#?

**Comment by citizenmatt** [comment]
From what I can see, it's because Exude creates a test command for each test case without changing the default display name, which is the method name. This means the three test cases are created with the same name. Xunit v1 uses type name, method name and display name as the only identifying features of a test, so the ReSharper runner sees them all as the same test.

By contrast, xunit's normal theory support creates a unique(-ish) name for each command, based on the method name and the parameters being passed, so I can tell that they need to be new nodes in the tree. 

That said, there is some code to look for duplicate names in theories, as it's easy to pass in duplicate values, or use a user-defined type that doesn't implement `ToString`. I guess this needs extending to handle duplicate methods (although giving the commands a unique display name would also fix it).
