### ISSUE TITLE
Viewing Console.Out, Console.Error and Debug.WriteLine

### ISSUE THREAD

**Issue by drewnoakes** [xunit/resharper-xunit#42]
With NUnit tests, output written to `Console.Out`, `Console.Error` or `Debug.Write*` appears in the detail area when the test is selected.

I cannot seem to get any test output to appear in the same panel via the xunit test runner.

Am I doing it wrong?

xUnit Test Support 2.0.5
VS2013 Community 12.0.31101.00 Update 4
ReSharper 9.0 Update 1

**Comment by citizenmatt** [comment]
This is probably due to a change in xunit2 - it no longer supports capturing `Console.Out` or `Console.Error`, etc. because it's now multi-threaded, and there's no way to know which test made the output. What you can do instead is take an instance of `ITestOutputHelper` in your test constructor arguments and use that to output any messages you need.

I don't think this has made it to the [xunit docs site](http://xunit.github.io) yet, but you can read a little about it in the [release notes from March](http://xunit.github.io/release-notes/2015-03-16.html) (scroll down to "Test Output").

**Comment by bradwilson** [comment]
I just pushed a documentation page today. Hopefully that will clear things up. :)

http://xunit.github.io/docs/capturing-output.html

**Comment by drewnoakes** [comment]
Thanks both for your help with this issue, and for your work on the tool in general.

**Comment by weitzhandler** [comment]
Is there a way to run xUnit as a CLI and have logging printed out to it?
