### ISSUE TITLE
Theory with a single AutoFixture custom attribute shows as two tests (one passes and one not run)

### ISSUE THREAD

**Issue by eroller** [xunit/resharper-xunit#65]
![image](https://cloud.githubusercontent.com/assets/2440289/8579197/015949ce-2568-11e5-9647-ca6f30360ba5.png)

**Comment by eroller** [comment]
The workaround from https://github.com/xunit/xunit/issues/460 has no effect

**Comment by citizenmatt** [comment]
This is normal behaviour, because the data is random, and so the name of the test that is run is also random, and different on each run. The first time you run the test, only one theory is shown under the `MyTest` node. The second time you run the test, that theory doesn't get re-run (it's using a different guid based value). Instead, a new value is run. This is treated as a new theory (because it is), and the old one is marked as not having run, and a new one is added.

**Comment by eroller** [comment]
Thanks! Building the solution removes the test that was not run, leaving only the results from the last test that was run.
