### ISSUE TITLE
Framework:automatic

### ISSUE THREAD

**Issue by danielwertheim** [xunit/resharper-xunit#78]
Using xUnit v2, VS2015, ReSharper 9.2 Ultimate

When you have tests that targets different frameworks, e.g. Net4.6, PCL (net46, aspnetcore, uap10) and running with automatic for framework it seems to pick .Net4.0, why? Why not 4.5?

When running the tests in xunit console it is executes correctly, also in the Test Explorer.

The test you can use to reproduce this behavior is this:

```csharp
public class FooTests
{
    [Fact]
    public void It_shall_be_encoded()
    {
        Assert.Equal(
            "http://localhost:5984/mydb/test%2F1",
            new Uri("http://localhost:5984/mydb/test%2F1").ToString());
    }
}
```

This should fail in .Net4.0 and work in .Net4.6 as there's different behaviour in there (http://danielwertheim.se/2014/10/11/uri-behaves-differently-in-net4-0-vs-net4-5/) 

But I would expect it to NOT execute with .Net4.0 when on automatic.

![xunit-resharper-framework](https://cloud.githubusercontent.com/assets/196044/9699757/0f947de2-53ee-11e5-853f-2faad67ce8e9.PNG)
![xunit-resharper-framework-explicit](https://cloud.githubusercontent.com/assets/196044/9699755/0f91ddee-53ee-11e5-8b49-e8648c0715b4.PNG)
![xunit-console-runner](https://cloud.githubusercontent.com/assets/196044/9699756/0f9472e8-53ee-11e5-9239-f5e6273efb5a.PNG)
![xunit-testexplorer](https://cloud.githubusercontent.com/assets/196044/9699758/0f962c6e-53ee-11e5-9465-7582080d99a5.PNG)

**Comment by rogeralsing** [comment]
Nice!!

**Comment by danielwertheim** [comment]
In the best of worlds, it should pick the target framework of the project that "hosts" the tests, that would (at least in my brain) be the easiest to understand. If prereq aren't met, do not fall back on other frameworks. E.g. run 4.0 in 4.5, at least not silently.

**Comment by citizenmatt** [comment]
Sadly, another ReSharper bug - the same thing happens for nunit. ReSharper has runners for .net 2 (and therefore 3/3.5), .net 4.0 and .net 4.5. It doesn't have a .net 4.6 runner. Annoyingly, it does appear to fall back to .net 4.0, instead of .net 4.5.

Here's the issue for creating a .net 4.6 app - [RSRP-446265](https://youtrack.jetbrains.com/issue/RSRP-446265).

The only decent workaround for this is to set the framework to 4.5 in ReSharper &rarr; Options &rarr; Unit Testing ("Force tests to use CLR 4.5"). If you click Save To, you can save to the "Team Shared" settings file, which creates a `.sln.dotSettings` file that sits beside the solution file, and can be checked into source control.

**Comment by danielwertheim** [comment]
Thanks. Commented in YouTrack.

Not sure if I think that "force tests to use CLR 4.5" is good, since you might have some projects that should be 4.0. That would force two solutions with different dotSettings.
